//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pavilion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pavilion()
        {
            this.rent = new HashSet<rent>();
        }
    
        public int pavilionID { get; set; }
        public int shoppingCenterID { get; set; }
        public string pavilionNumber { get; set; }
        public int floor { get; set; }
        public int pavilionStatusID { get; set; }
        public decimal square { get; set; }
        public decimal costForMetere { get; set; }
        public decimal coefficientOfAddedCost { get; set; }
    
        public virtual pavilionStatus pavilionsStatuses { get; set; }
        public virtual shoppingCenter shoppingCenters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rent { get; set; }
    }
}
