//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shoppingCenter()
        {
            this.pavilions = new HashSet<pavilion>();
        }
    
        public int shoppingCenterID { get; set; }
        public string shoppingCenterName { get; set; }
        public int shoppingCenterStatusID { get; set; }
        public int numberOfPavilions { get; set; }
        public string city { get; set; }
        public decimal cost { get; set; }
        public decimal coefficientOfAddedCost { get; set; }
        public int numberOfFloors { get; set; }
        public byte[] picShoppingCenter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pavilion> pavilions { get; set; }
        public virtual shoppingCentersStatus shoppingCentersStatuses { get; set; }
    }
}
