//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingCentersStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shoppingCentersStatus()
        {
            this.shoppingCenters = new HashSet<shoppingCenter>();
        }
    
        public int shoppingCenterStatusID { get; set; }
        public string shoppingCenterStatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shoppingCenter> shoppingCenters { get; set; }
    }
}
